name: Very Good Flutter Analyze

on: 
  pull_request:
    paths:
      - "lib"
  push:
    branches:
      - master
    paths:
      - "lib"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      min_coverage: 75
      flutter_channel: stable
      flutter_version: 2.10.0
